update scripts from padraig

diff --git a/lp b/lp
--- a/lp
+++ b/lp
@@ -14,7 +14,7 @@
 #                       Don't error for ls without --group-dir or --no-group
 #    V0.3, 21 Oct 2009, Handle older ls' which pepper output with reset codes
 #
-#    V1.0, 04 Oct 2010
+#    V1.4, 21 Nov 2016
 #      http://github.com/pixelb/scripts/commits/master/scripts/l
 
 # apply thousands separator to file sizes
@@ -61,11 +61,11 @@ else
 fi
 
 ls=ls #default to standard name
-
-$ls --color -d . >/dev/null 2>&1 || BSD=1
+{ ls --color -d . >/dev/null 2>&1; } ||
+{ gls --color -d . >/dev/null 2>&1 && ls=gls; } || NONGNU=1
 
 if [ "$color_when" ]; then
-  if [ "$BSD" ]; then
+  if [ "$NONGNU" ]; then
     { colorls -d .; } >/dev/null 2>&1 && ls=colorls # for OpenBSD
     $ls -G -d . >/dev/null 2>&1 && color_opt=-G #not supported on Solaris
     [ "$color_when" = "always" ] && { CLICOLOR_FORCE=1; export CLICOLOR_FORCE; }
@@ -94,12 +94,17 @@ if [ "$color_when" ]; then
     # as it defaults to blinking.  We could do all this in ~/.dir_colors
     # but so this script is more general, we do it here.
 
+    # Ensure LS_COLORS is delimited with ':' to simplify the following regexes.
+    # Otherwise we'd have to consider using word boundaries (\b, \<, [[:<:]]),
+    # but those are non portable.
+    LS_COLORS=":$LS_COLORS:"; export LS_COLORS
+
     # Newer ls use "mh" to represent the color for multi hardlinked
-    # files so handle the backwards incompatability with "hl"
-    if   dircolors | grep -F "mh=" >/dev/null; then
-      hl_no_color="s/hl[^:]*:/mh=:/; s/mh[^:]*:/mh=:/"
+    # files so handle the backwards incompatibility with "hl"
+    if   dircolors | grep -F ":mh=" >/dev/null; then
+      hl_no_color="s/:hl=[^:]*:/:mh=:/; s/:mh=[^:]*:/:mh=:/"
     elif dircolors | grep -F "hl=" >/dev/null; then
-      hl_no_color="s/mh[^:]*:/hl=:/; s/hl[^:]*:/hl=:/"
+      hl_no_color="s/:mh=[^:]*:/:hl=:/; s/:hl=[^:]*:/:hl=:/"
     fi
 
     # The extra quoting (wrapping in "") is required for
@@ -111,15 +116,15 @@ if [ "$color_when" ]; then
 
       sed \"
         $hl_no_color
-        s/su[^:]*:/su=:/
-        s/sg[^:]*:/sg=:/
-        s/ow[^:]*:/ow=:/
-        s/st[^:]*:/st=:/
-        s/tw[^:]*:/tw=:/
+        s/:su=[^:]*:/:su=:/
+        s/:sg=[^:]*:/:sg=:/
+        s/:ow=[^:]*:/:ow=:/
+        s/:st=[^:]*:/:st=:/
+        s/:tw=[^:]*:/:tw=:/
 
-        s/ca[^:]*:/ca=:/
+        s/:ca=[^:]*:/:ca=:/
 
-        s/mi=[^:]\{1,\}:/mi=$LS_HLI:/
+        s/:mi=[^:]\{1,\}:/:mi=$LS_HLI:/
       \"
 
       echo 'export LS_COLORS'
@@ -132,15 +137,24 @@ total=`$ls -s $color_never / | sed 's/\([^ ]*\).*/\1/;q'`
 # Use these options if available
 $ls --group-directories-first -d . >/dev/null 2>&1 && gdf=--group-directories
 $ls --no-group -d . >/dev/null 2>&1 && ng=--no-group
+$ls --quoting=shell-escape -d . >/dev/null 2>&1 && quote=--quoting=shell-escape
 
 # Bypass long format manipulation if any of following formats are specified
 # FIXME: Matching options like this is a bit brittle
 lfmt=lfmt
-echo "$*" | grep -E -- "-(i|x|s|C|-version|-help)" >/dev/null && lfmt=""
+echo "$*" | grep -E -- "-(m|i|x|s|C|-version|-help)" >/dev/null && lfmt=""
+
+# set -o pipefail is bash/ksh/zsh specific
+# So manually propagate the exit status from ls.
+# See http://stackoverflow.com/a/30658405/4421
+
+exec 4>&1
+ls_status=`{ {
 
 # Start with the standard long format listing
 # with colours, and latest files at bottom
-$ls -lrtq $color_opt$color_when $ng $gdf "$@" |
+$ls -lrtq $color_opt$color_when $ng $gdf $quote "$@";
+printf $? 1>&3; } |
 
 # process with sed to...
 sed "
@@ -180,5 +194,14 @@ sed "
   :not_hl
 
   # restore any reset codes replaced above
-  s/^0/$ESC[0m/
-"
+  s/^0/${ESC}[0m/
+" 1>&4; } 3>&1`
+
+sed_status=$?
+
+# Note if sed fails, then if ls outputs it will usually get
+# a SIGPIPE and exit with status 141.  Though that's dependent
+# on ls(1) propagating that "error", and also will not be the case
+# if ls does not output after sed terminates.  So factor both
+# exit values into the final exit status.
+test $ls_status != 0 && exit $ls_status || exit $sed_status
